name: Validate Modules

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: "${{ matrix.module }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        module:
          - modules/cloudfunction/v0.0.1
          - modules/manageddb/v0.0.1
          - modules/objectstorage/v0.0.1
          - applications/poseidon/v0.0.1
          - applications/poseidon/v0.0.2
          - applications/zeus/v0.0.1

    defaults:
      run:
        working-directory: ${{ matrix.module }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: terraform init
        run: terraform init -backend=false

      - name: terraform validate
        run: terraform validate
